services:
  db:
    container_name: IHearYouDB
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: IHearYouRedis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  bot:
    build:
      context: .
      target: bot
    container_name: IHearYouBot
    env_file: .env
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./bot
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile

  bot_api:
    build:
      context: .
      target: admin
    container_name: IHearYouAdminAPI
    env_file: .env
    environment:
      ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY:-changeme}
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - db
      - redis
    ports:
      - "${BOT_API_PORT:-8001}:8000"
    volumes:
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
      - ./backend:/app/backend
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Loading flow data...' &&
        python backend/load_flow_data.py &&
        echo 'Starting API server...' &&
        uvicorn backend.main:app --host 0.0.0.0 --port 8000
      "
    develop:
      watch:
        - action: rebuild
          path: ./backend
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile

  celery_worker:
    build:
      context: .
      target: admin
    container_name: IHearYouCelery
    env_file: .env
    environment:
      ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY:-changeme}
      BOT_TOKEN: ${BOT_TOKEN}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - redis
    volumes:
      - ./backend:/app/backend
    command: ["celery", "-A", "backend.core.celery_app.celery_app", "worker", "-l", "info", "-Q", "celery"]
  bot_frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${FRONTEND_API_URL:-http://localhost:8001/api}
    container_name: IHearYouAdminFrontend
    environment:
      VITE_API_URL: ${FRONTEND_API_URL:-http://localhost:8001/api}
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    command: ["serve", "-s", "dist", "-l", "3001"]
    depends_on:
      - bot_api
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src
        - action: rebuild
          path: ./frontend/public
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
        - action: rebuild
          path: ./frontend/Dockerfile

  pgadmin:
    container_name: IHearYouPgAdmin
    image: dpage/pgadmin4:latest
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-8080}:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pg_data:
  pgadmin_data:

