services:
  db:
    container_name: IHearYouDB
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
      target: bot
    container_name: IHearYouBot
    env_file: .env
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./bot
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile

  bot_api:
    build:
      context: .
      target: admin
    container_name: IHearYouAdminAPI
    env_file: .env
    environment:
      ADMIN_SECRET_KEY: ${ADMIN_SECRET_KEY:-changeme}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - db
    ports:
      - "${BOT_API_PORT:-8001}:8000"
    volumes:
      - ./backend/alembic/versions:/app/alembic/versions
      - ./backend/alembic.ini:/app/alembic.ini
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        echo 'Running migrations...' &&
        alembic upgrade head &&
        echo 'Starting API server...' &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    develop:
      watch:
        - action: rebuild
          path: ./backend
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./Dockerfile

  bot_frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${FRONTEND_API_URL:-http://localhost:8001/api}
    container_name: IHearYouAdminFrontend
    environment:
      VITE_API_URL: ${FRONTEND_API_URL:-http://localhost:8001/api}
    ports:
      - "${FRONTEND_PORT:-3001}:3001"
    command: ["serve", "-s", "dist", "-l", "3001"]
    depends_on:
      - bot_api
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src
        - action: rebuild
          path: ./frontend/public
        - action: rebuild
          path: ./frontend/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
        - action: rebuild
          path: ./frontend/Dockerfile

volumes:
  pg_data:
