"""Delete Notification, amend Remainder_template

Revision ID: 2029a01863c3
Revises: e8a9cd7e3164
Create Date: 2025-10-01 14:21:30.096493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2029a01863c3'
down_revision: Union[str, None] = 'e8a9cd7e3164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_id', table_name='notifications')
    op.drop_index('ix_notifications_telegram_user_id', table_name='notifications')
    op.drop_index('ix_notifications_template_id', table_name='notifications')
    op.drop_table('notifications')
    op.add_column('reminder_templates', sa.Column('inactive_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminder_templates', 'inactive_days')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['telegram_users.id'], name='notifications_telegram_user_id_fkey'),
    sa.ForeignKeyConstraint(['template_id'], ['reminder_templates.id'], name='notifications_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('ix_notifications_template_id', 'notifications', ['template_id'], unique=False)
    op.create_index('ix_notifications_telegram_user_id', 'notifications', ['telegram_user_id'], unique=False)
    op.create_index('ix_notifications_id', 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###
