"""Инициализация схем и экспорт."""

# Административные схемы
from .admin import (
    AdminAnalyticsRequest,
    AdminAnalyticsResponse,
    AdminContentFileCreate,
    AdminContentFileResponse,
    AdminContentFileUpdate,
    AdminLoginRequest,
    AdminLoginResponse,
    AdminMenuItemCreate,
    AdminMenuItemListResponse,
    AdminMenuItemResponse,
    AdminMenuItemUpdate,
    AdminMeResponse,
    AdminMessageTemplateCreate,
    AdminMessageTemplateListResponse,
    AdminMessageTemplateResponse,
    AdminMessageTemplateUpdate,
    AdminNotificationListResponse,
    AdminNotificationRequest,
    AdminNotificationResponse,
    AdminNotificationUpdate,
    AdminPasswordResetConfirmRequest,
    AdminPasswordResetRequest,
    AdminPasswordResetSuccessResponse,
    AdminQuestionAnswer,
    AdminQuestionListResponse,
    AdminQuestionResponse,
    AdminRefreshRequest,
    AdminRefreshResponse,
    AdminTelegramUserListResponse,
    AdminTelegramUserResponse,
    AdminUserCreate,
    AdminUserListResponse,
    AdminUserPasswordUpdate,
    AdminUserResponse,
    AdminUserUpdate,
)
from .bot.message_template import BotMessageTemplateResponse

# Bot API схемы
from .bot.telegram_user import TelegramUserRequest, TelegramUserResponse

# Публичные схемы
from .public import (
    ContentFileResponse,
    MenuContentResponse,
    MenuItemResponse,
    RatingRequest,
    RatingResponse,
    SearchListResponse,
    UserActivityRequest,
    UserActivityResponse,
    UserQuestionCreate,
    UserQuestionResponse,
)


__all__ = [
    # Admin schemas
    "AdminLoginRequest",
    "AdminLoginResponse",
    "AdminRefreshRequest",
    "AdminRefreshResponse",
    "AdminMeResponse",
    "AdminPasswordResetRequest",
    "AdminPasswordResetConfirmRequest",
    "AdminPasswordResetSuccessResponse",
    "AdminAnalyticsRequest",
    "AdminAnalyticsResponse",
    "AdminMenuItemResponse",
    "AdminMenuItemCreate",
    "AdminMenuItemUpdate",
    "AdminMenuItemListResponse",
    "AdminContentFileResponse",
    "AdminContentFileCreate",
    "AdminContentFileUpdate",
    "AdminNotificationRequest",
    "AdminNotificationResponse",
    "AdminNotificationListResponse",
    "AdminNotificationUpdate",
    "AdminQuestionResponse",
    "AdminQuestionListResponse",
    "AdminQuestionAnswer",
    "AdminMessageTemplateResponse",
    "AdminMessageTemplateListResponse",
    "AdminMessageTemplateCreate",
    "AdminMessageTemplateUpdate",
    "AdminTelegramUserResponse",
    "AdminTelegramUserListResponse",
    "AdminUserResponse",
    "AdminUserListResponse",
    "AdminUserCreate",
    "AdminUserUpdate",
    "AdminUserPasswordUpdate",
    # Public schemas
    "MenuItemResponse",
    "MenuContentResponse",
    "ContentFileResponse",
    "RatingRequest",
    "RatingResponse",
    "SearchListResponse",
    "UserActivityRequest",
    "UserActivityResponse",
    "UserQuestionCreate",
    "UserQuestionResponse",
    # Bot API schemas
    "TelegramUserRequest",
    "TelegramUserResponse",
    "BotMessageTemplateResponse",
]
